### ISSUE TITLE
Widget Explorer to manage from PythonQt

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#79]
Hello Shing,
Please, it it possible to add Explorer widget to PipeCad.Core to provide ability of it management from PythonQt. Call from Python could be like that:
```python
explorer_widget = PipeCad.Explorer('Design', '/*')  # where: Design, Catalogue, Admin - module name; /* - World element of selected MDB
explorer_widget.setTitle('Design Explorer')
explorer_widget.setFilter(|SAM-PIPE-*|)         # To filter all SITEs started with SAM-PIPE-
# or 
explorer_widget.setFilter(|SAM-PIPE-|)          # To filter only SITE with exact name SAM-PIPE-
CE = explorer_widget.selectedItem()            # get selected element
filtered_items = explorer_widget.getFilteredItems(|SAM-PIPE-*|)    # list of filtered sites in according with condition
```
![изображение](https://user-images.githubusercontent.com/12736532/177940565-13e9086c-29e8-4fa8-8c98-0c6ea1fbda86.png)

**Comment by eryar** [comment]
Hello Roman,

Some user may not find items due to inadvertent use of filtering.
So I removed the filter function of Explorer.

But the filter function is useful for advanced user, you can use 
` PipeCad.SearchItem(theKeyword, theType)`
If theType is empty, will search all type items contains theKeyword:

![image](https://user-images.githubusercontent.com/8439181/178086411-c4832232-b15b-4a1e-89ce-134d21d49325.png)

**Comment by rompik** [comment]
Noted. Thank you!
